name: Testing

on: push

env:
  DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING}}

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v4

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
